name: CMake

on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    
    runs-on: [ubuntu-latest,windows-latest]  

    steps:
    - uses: actions/checkout@v3

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/projekt_kod/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/projekt_kod/build
      run: cmake $GITHUB_WORKSPACE/projekt_kod -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/projekt_kod/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{github.workspace}}/projekt_kod/build
      shell: bash
      run: ctest -C $BUILD_TYPE
